### ISSUE TITLE
npm install phonon fails v1.4.0 

### ISSUE THREAD

**Issue by sday** [quark-dev/Phonon-Framework#216]
During the postinstall phase the installer appears to be running a gulp task that isn't specified.  Am I missing something obvious?

```
bash-3.2$ npm install phonon

> phonon@1.4.0 postinstall /Users/steve/project/node_modules/phonon
> gulp


assert.js:85
  throw new assert.AssertionError({
  ^
AssertionError: Task function must be specified
    at Gulp.set [as _setTask] (/Users/steve/project/node_modules/undertaker/lib/set-task.js:10:3)
    at Gulp.task (/Users/steve/project/node_modules/undertaker/lib/task.js:13:8)
    at Object.<anonymous> (/Users/steve/project/node_modules/phonon/gulpfile.js:12:6)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
npm ERR! Darwin 16.4.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "phonon"
npm ERR! node v6.9.5
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! phonon@1.4.0 postinstall: `gulp`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the phonon@1.4.0 postinstall script 'gulp'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the phonon package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     gulp
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs phonon
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls phonon
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/steve/project/npm-debug.log
```

**Comment by John-Henrique** [comment]
Problem similar when using bower...
```
>bower install phonon
bower not-cached    https://github.com/quark-dev/Phonon-Framework.git#*
bower resolve       https://github.com/quark-dev/Phonon-Framework.git#*
bower ECMDERR       Failed to execute "git ls-remote --tags --heads https://github.com/quark-dev/Phonon-Framework.git", exit code of #1
```

**Comment by Qathom** [comment]
Hi @sday and @John-Henrique,

The bug has been fixed! Please can you try to run `npm install phonon` again?
Please, reopen this issue if it is not fixed since **[v1.4.2](https://github.com/quark-dev/Phonon-Framework/releases/tag/v1.4.2)**.

**Comment by John-Henrique** [comment]
Tested

**BOWER**
```
bower install phonon
bower not-cached    https://github.com/quark-dev/Phonon-Framework.git#*
bower resolve       https://github.com/quark-dev/Phonon-Framework.git#*
bower ECMDERR       Failed to execute "git ls-remote --tags --heads https://github.com/quark-dev/Phonon-Framework.git", exit code of #1
```
Failed


**NPM**
```
npm -g install phonon
C:\Users\johnh\AppData\Roaming\npm
`-- phonon@1.4.3
  +-- awesomplete@1.1.1
  `-- platform@1.3.3
```

Works.

@Qathom 
Replaced "dist" by "src" directory?

**Comment by Qathom** [comment]
@John-Henrique : try to delete the folder `bower_components` and try again to run `bower install phonon`.

**Comment by John-Henrique** [comment]
Not working. I delete folder and run again "bower install phonon", same error.
